server:
  servlet:
    encoding:
      charset: utf-8
      force: true

  # 포트 8080 << default
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
  jpa:
    hibernate:
      #실제 서버를 가동할때는 ddl-auto을 none으로 해야한다.
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        # JPA의 format_sql << 쿼리를 보기좋게 만들어줌
        format_sql: true

  # output.ansi << console창에 색상부여, 저장시 서버자동 재실행
  output:
    ansi:
      enabled: always
