server:
  servlet:
    encoding:
      charset: utf-8
      force: true

  # 포트 8080 << default
  port: 8080

# h2는 메모리데이터로 가짜 DB, 스프링이 켜질때 같이 켜졌다가 같이 꺼짐
# MODE를 설정(방언을 설정)해서 DBMS처럼 사용할수 있다.
spring:
  mustache:
    servlet:
      #  mustache 에서 session에 접근할수 있게 true
      expose-session-attributes: true

      #  mustache 에서 request 접근할수 있게 true
      expose-request-attributes: true

  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations:
        # 클래스패스를 등록해놓아야 그 안에 있는 데이터(java파일, 데이터파일 등) 가져올수있다.
        - classpath:db/data.sql
  jpa:
    # defer-datasource-initialization: true << 테이블이 가장 먼저 만들어지게 하는 명령어
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # JPA의 format_sql << 쿼리를 보기좋게 만들어줌

  output:
    ansi:
      enabled: always
