spring:
  profiles:
    active:
      - dev # 실행되는 설정파일명을 기입 "- dev"일때 -dev이름을 가진 파일이 실행

# 포트 8080 << default
# h2는 메모리데이터로 가짜 DB, 스프링이 켜질때 같이 켜졌다가 같이 꺼짐
# MODE를 설정(방언을 설정)해서 DBMS처럼 사용할수 있다.
# JPA의 format_sql << 쿼리를 보기좋게 만들어줌
